(define (problem medium)
    (:domain the_game)
    (:objects
        pile0 pile1 - pile
        c_min c_max c3 c15 c9 c10 c2 c4 c12 c17 c6 c8 c14 c16 c5 c7 c11 c19 c13 c18 - card
    )
    (:init
        (ascending_pile pile0)
        (descending_pile pile1)
        (top_pile_card pile0 c_min)
        (top_pile_card pile1 c_max)
        (top_deck_card c3)
        (next_card_in_deck c3 c15)
        (next_card_in_deck c15 c9)
        (next_card_in_deck c9 c10)
        (next_card_in_deck c10 c2)
        (next_card_in_deck c2 c4)
        (next_card_in_deck c4 c12)
        (next_card_in_deck c12 c17)
        (next_card_in_deck c17 c6)
        (next_card_in_deck c6 c8)
        (next_card_in_deck c8 c14)
        (next_card_in_deck c14 c16)
        (next_card_in_deck c16 c5)
        (next_card_in_deck c5 c7)
        (next_card_in_deck c7 c11)
        (next_card_in_deck c11 c19)
        (next_card_in_deck c19 c13)
        (next_card_in_deck c13 c18)
        (is_bottom_card c18)
        (= (n_card_in_hand) 0)
        (= (value c_min) 1)
        (= (value c_max) 20)
        (= (value c3) 3)
        (= (value c15) 15)
        (= (value c9) 9)
        (= (value c10) 10)
        (= (value c2) 2)
        (= (value c4) 4)
        (= (value c12) 12)
        (= (value c17) 17)
        (= (value c6) 6)
        (= (value c8) 8)
        (= (value c14) 14)
        (= (value c16) 16)
        (= (value c5) 5)
        (= (value c7) 7)
        (= (value c11) 11)
        (= (value c19) 19)
        (= (value c13) 13)
        (= (value c18) 18)
    )
    (:goal
        (and
            (deck_empty)
            (= (n_card_in_hand) 0)
        )
    )
)
